framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]
    session:
        name: _sid
        handler_id: redis://cache
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
